# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Xcode Setup
      uses: csaba-turdesan/setup-xcode@v1
      with:
        xcode-version: '16.1'
    - name: Code Setup
      run: swift build -v
    - name: Run tests
      run: swift test -v
