name: Xcode CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: |
          xcodebuild -version

      - name: Build the Project
        run: |
          xcodebuild -scheme YourSchemeName -sdk iphoneos -configuration Release build

      - name: Run Tests
        run: |
          xcodebuild -scheme YourSchemeName -sdk iphonesimulator -configuration Debug test
